/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  checkPath: () => checkPath,
  default: () => ColorfulNoteBackgroundPlugin,
  hexToRgbA: () => hexToRgbA
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/settingsTab.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  colorRules: [
    {
      id: "inbox-ffb300",
      value: "Inbox",
      type: "folder" /* Folder */,
      color: "#ffb300",
      alpha: 0.04
    },
    {
      id: "frontmatter-public-499749",
      value: "category: public",
      type: "frontmatter" /* Frontmatter */,
      color: "#499749",
      alpha: 0.04
    },
    {
      id: "frontmatter-private-c44545",
      value: "category: private",
      type: "frontmatter" /* Frontmatter */,
      color: "#c44545",
      alpha: 0.04
    }
  ]
};
var SettingsTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.addClass("cnb-settings");
    containerEl.createEl("p", {
      text: "Add rules to color note backgrounds. Rules are matched in order\u2014first match wins (priority).",
      cls: "setting-item-description"
    });
    const table = containerEl.createEl("div", { cls: "cnb-rules-table" });
    const header = table.createEl("div", { cls: "cnb-rules-header" });
    header.createEl("span", { text: "Type" });
    header.createEl("span", { text: "Value" });
    header.createEl("span", { text: "Color" });
    header.createEl("span", { text: "Alpha" });
    header.createEl("span", { text: "Priority" });
    header.createEl("span", { text: "" });
    const rulesContainer = table.createEl("div", { cls: "cnb-rules-body" });
    this.renderRules(rulesContainer);
    new import_obsidian.Setting(containerEl).addButton((btn) => {
      btn.setButtonText("Add rule").setCta().onClick(() => {
        const newRule = {
          id: Date.now().toString(),
          value: "",
          type: "folder" /* Folder */,
          color: "#3b82f6",
          alpha: 0.04
        };
        this.plugin.settings.colorRules.push(newRule);
        void this.plugin.saveSettings();
        this.renderRules(rulesContainer);
      });
    });
  }
  renderRules(container) {
    container.empty();
    this.plugin.settings.colorRules.forEach((rule, index) => {
      this.addRuleRow(container, rule, index);
    });
  }
  addRuleRow(container, rule, index) {
    var _a, _b;
    const row = container.createEl("div", { cls: "cnb-rule-row" });
    const typeCell = row.createEl("div", { cls: "cnb-cell" });
    new import_obsidian.DropdownComponent(typeCell).addOption("folder" /* Folder */, "Folder").addOption("frontmatter" /* Frontmatter */, "Frontmatter").setValue(rule.type).onChange((value) => {
      rule.type = value;
      void this.plugin.saveSettings();
    });
    const valueCell = row.createEl("div", { cls: "cnb-cell" });
    new import_obsidian.TextComponent(valueCell).setPlaceholder(rule.type === "folder" /* Folder */ ? "Folder name" : "key: value").setValue(rule.value).onChange((value) => {
      rule.value = value;
      void this.plugin.saveSettings();
    });
    const colorCell = row.createEl("div", { cls: "cnb-cell cnb-color-cell" });
    const colorInput = new import_obsidian.TextComponent(colorCell).setValue(rule.color);
    colorInput.inputEl.addClass("cnb-color-input");
    const picker = new import_obsidian.ColorComponent(colorCell).setValue(rule.color).onChange((color) => {
      rule.color = color;
      colorInput.setValue(color);
      void this.plugin.saveSettings();
    });
    colorInput.onChange((value) => {
      if (/^#(?:[0-9a-fA-F]{3}){1,2}$/.test(value)) {
        rule.color = value;
        picker.setValue(value);
        void this.plugin.saveSettings();
      }
    });
    const alphaCell = row.createEl("div", { cls: "cnb-cell" });
    const alphaInput = new import_obsidian.TextComponent(alphaCell).setValue((_b = (_a = rule.alpha) == null ? void 0 : _a.toString()) != null ? _b : "0.04");
    alphaInput.inputEl.type = "number";
    alphaInput.inputEl.step = "0.01";
    alphaInput.inputEl.min = "0";
    alphaInput.inputEl.max = "1";
    alphaInput.inputEl.addClass("cnb-alpha-input");
    alphaInput.onChange((value) => {
      const num = parseFloat(value);
      if (!isNaN(num) && num >= 0 && num <= 1) {
        rule.alpha = num;
        void this.plugin.saveSettings();
      }
    });
    const priorityCell = row.createEl("div", { cls: "cnb-cell cnb-priority-cell" });
    new import_obsidian.ButtonComponent(priorityCell).setIcon("chevron-up").setTooltip("Move up (higher priority)").setDisabled(index === 0).onClick(() => {
      this.plugin.settings.colorRules.splice(index, 1);
      this.plugin.settings.colorRules.splice(index - 1, 0, rule);
      void this.plugin.saveSettings();
      this.renderRules(container);
    });
    new import_obsidian.ButtonComponent(priorityCell).setIcon("chevron-down").setTooltip("Move down (lower priority)").setDisabled(index === this.plugin.settings.colorRules.length - 1).onClick(() => {
      this.plugin.settings.colorRules.splice(index, 1);
      this.plugin.settings.colorRules.splice(index + 1, 0, rule);
      void this.plugin.saveSettings();
      this.renderRules(container);
    });
    const deleteCell = row.createEl("div", { cls: "cnb-cell cnb-delete-cell" });
    new import_obsidian.ButtonComponent(deleteCell).setIcon("x").setTooltip("Delete rule").onClick(() => {
      this.plugin.settings.colorRules = this.plugin.settings.colorRules.filter((r) => r.id !== rule.id);
      void this.plugin.saveSettings();
      this.renderRules(container);
    });
  }
};

// src/main.ts
var checkPath = (currentPath, folder) => {
  const parts = currentPath.split(/[/\\]/);
  return parts.includes(folder);
};
function hexToRgbA(hex, alpha) {
  let c = hex.replace("#", "");
  if (c.length === 3) c = c.split("").map((x) => x + x).join("");
  const num = parseInt(c, 16);
  const r = num >> 16 & 255;
  const g = num >> 8 & 255;
  const b = num & 255;
  return `rgba(${r},${g},${b},${alpha})`;
}
var ColorfulNoteBackgroundPlugin = class extends import_obsidian2.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new SettingsTab(this.app, this));
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", this.onActiveLeafChange.bind(this))
    );
    this.registerEvent(
      this.app.metadataCache.on("changed", this.onMetadataChange.bind(this))
    );
    this.registerEvent(
      this.app.vault.on("rename", this.onFileRename.bind(this))
    );
  }
  onunload() {
    this.app.workspace.getLeavesOfType("markdown").forEach((leaf) => {
      if (!(leaf.view instanceof import_obsidian2.MarkdownView)) return;
      const contentView = leaf.view.containerEl.querySelector(".view-content");
      if (contentView) {
        this.unhighlightNote(contentView);
      }
    });
  }
  onActiveLeafChange(activeLeaf) {
    this.applyRules();
  }
  onMetadataChange(file) {
    this.applyRules(file);
  }
  onFileRename(file) {
    this.applyRules();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    const activeFile = this.app.workspace.getActiveFile();
    if (activeFile) {
      this.onFileRename(activeFile);
    }
  }
  applyRules(file = null) {
    this.app.workspace.getLeavesOfType("markdown").forEach((value) => {
      if (!(value.view instanceof import_obsidian2.MarkdownView)) return;
      const activeView = value.view;
      const viewFile = activeView.file;
      if (!viewFile) return;
      if (file && file !== viewFile) return;
      const contentView = activeView.containerEl.querySelector(".view-content");
      if (!contentView) return;
      this.unhighlightNote(contentView);
      this.settings.colorRules.some((rule) => {
        return this.applyRule(viewFile, rule, contentView);
      });
    });
  }
  applyRule(file, rule, contentView) {
    var _a, _b;
    switch (rule.type) {
      case "folder" /* Folder */: {
        if (checkPath(file.path, rule.value)) {
          this.highlightNote(contentView, rule);
          return true;
        }
        break;
      }
      case "frontmatter" /* Frontmatter */: {
        const [key, value] = rule.value.split(":", 2);
        const frontMatterValue = (_b = (_a = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter) == null ? void 0 : _b[key];
        const normalizedFrontMatterValue = frontMatterValue == null ? void 0 : frontMatterValue.toString().toLowerCase().trim();
        const normalizedValueToHighlight = value == null ? void 0 : value.toString().toLowerCase().trim();
        if (normalizedFrontMatterValue === normalizedValueToHighlight) {
          this.highlightNote(contentView, rule);
          return true;
        }
        break;
      }
    }
    return false;
  }
  highlightNote(element, rule) {
    const alpha = typeof rule.alpha === "number" ? rule.alpha : 1;
    const rgbaColor = hexToRgbA(rule.color, alpha);
    element.classList.add("cnb-highlighted");
    element.style.setProperty("--cnb-highlight-color", rgbaColor);
  }
  unhighlightNote(element) {
    element.classList.remove("cnb-highlighted");
    element.style.removeProperty("--cnb-highlight-color");
  }
};

/* nosourcemap */